#!/usr/bin/env bash
# PreToolUse: blocks any direct write to src/types/database.ts
# This file is auto-generated by `npm run supabase:types` — never edit manually

FILE_PATH="${CLAUDE_TOOL_INPUT_FILE_PATH:-}"

if [[ "$FILE_PATH" == *"src/types/database.ts" ]]; then
  echo "BLOCKED: src/types/database.ts is auto-generated. Run 'npm run supabase:types' to regenerate it. Never edit it directly." >&2
  exit 2
fi

exit 0