framework:
    workflows: 
        manage_app_deployments:
            type: 'state_machine'
            audit_trail:
                enabled: true
            marking_store:
                type: 'method'
                property: 'status'
            supports:
                - App\Entity\Deployments
            initial_marking: active
            places:
                - active
                - suspended
                - suspended_by_admin
                - stopped
                - archived
            transitions:
                stop:
                    from: active
                    to: stopped
                start:
                    from: stopped
                    to: active
                suspend:
                    from: active
                    to: suspended
                admin_suspend:
                    guard: "is_granted('ROLE_SUPPORT')"
                    from: active
                    to: suspended_by_admin
                reactivate:
                    from: suspended
                    to: active
                admin_reactivate:
                    guard: "is_granted('ROLE_SUPPORT')"
                    from: suspended_by_admin
                    to: active
                suspended_to_archive:
                    from: suspended
                    to: archived
                suspended_by_admin_to_archive:
                    from: suspended_by_admin
                    to: archived
                stopped_to_archive:
                    from: stopped
                    to: archived
        manage_organization_status:
            type: 'state_machine'
            audit_trail:
                enabled: true
            marking_store:
                type: 'method'
                property: 'status'
            supports:
                - App\Entity\Organization
            initial_marking: active
            places:
                - active
                - suspended
                - archived
                - pending_deletion
            transitions:
                suspend:
                    guard: "is_granted('ROLE_SUPPORT')"
                    from: active
                    to: suspended
                activate:
                    guard: "is_granted('ROLE_SUPPORT')"
                    from: suspended
                    to: active
                archive:
                # 6 months after the organization is archived, it is deleted from the database
                    guard: "is_granted('ROLE_SUPPORT')"
                    from: suspended
                    to: archived
                reactivate:
                    guard: "is_granted('ROLE_SUPPORT')"
                    from: archived
                    to: active
                delete:
                    guard: "is_granted('ROLE_SUPPORT')"
                    from: archived
                    to: pending_deletion