framework:
    workflows: 
        manage_app_deployments:
            type: 'state_machine'
            audit_trail:
                enabled: true
            marking_store:
                type: 'method'
                property: 'status'
            supports:
                - App\Entity\Deployments
            initial_marking: pending_deployment
            places:
                - pending_deployment
                - deploying
                - failed
                - active
                - stopped
                - suspended
                - archived
                - pending_deletion
            transitions:
                deploy:
                    from: pending_deployment
                    to: deploying
                fail:
                    from: [deploying, pending_deployment]
                    to: failed
                succeed:
                    from: deploying
                    to: active
                start:
                    from: [stopped, suspended]
                    to: active
                stop:
                    from: active
                    to: stopped
                suspend:
                    from: [active, pending_deployment, deploying]
                    to: suspended
                archive:
                    from: [suspended, stopped]
                    to: archived
                delete:
                    from: [archived, failed]
                    to: pending_deletion
        manage_organization_status:  
            type: 'state_machine'
            audit_trail:
                enabled: true
            marking_store:
                type: 'method'
                property: 'status'
            supports:
                - App\Entity\Organization
            initial_marking: active
            places:
                - active
                - disabled # when the organization is disabled by the support or admin
                - low_credit
                - no_credit
                - on_debt
                - suspended # when does not have credit
                - archived
                - pending_deletion
            transitions:
                suspend:
                    from: [on_debt, no_credit]
                    to: suspended
                archive:
                    from: [disabled, suspended]
                    to: archived
                delete:
                    guard: "is_granted('ROLE_SUPPORT')"
                    from: archived
                    to: pending_deletion
                consume_credit:
                    from: active
                    to: low_credit
                consume_low_credit:
                    from: low_credit
                    to: no_credit
                allow_credit_debt:
                    from: no_credit
                    to: on_debt
        manage_organization_status_via_staging:  
            type: 'state_machine'
            audit_trail:
                enabled: true
            marking_store:
                type: 'method'
                property: 'status'
            supports:
                - App\Entity\Organization
            initial_marking: active
            places:
                - active
                - disabled # when the organization is disabled by the support or admin
                - low_credit
                - no_credit
                - on_debt
                - suspended # when does not have credit
                - archived
                - staging # A temporary buffer state for when a state needs to go back to a previous state
            transitions:
                suspend:
                    from: [staging]
                    to: suspended
                reactivate:
                    guard: "is_granted('ROLE_SUPPORT')"
                    from: [archived, disabled]
                    to: staging
                add_transaction:
                    from: [suspended, active, low_credit, no_credit, on_debt]
                    to: staging
                activate:
                    from: staging
                    to: active
                go_to_lowcredit:
                    from: staging
                    to: low_credit
                go_to_nocredit:
                    from: staging
                    to: no_credit
                go_to_debt:
                    from: staging
                    to: on_debt