framework:
    workflows: 
        manage_app_deployments:
            type: 'state_machine'
            audit_trail:
                enabled: true
            marking_store:
                type: 'method'
                property: 'status'
            supports:
                - App\Entity\Deployments
            initial_marking: pending_deployment
            places:
                - pending_deployment
                - active
                - suspended
                - suspended_by_admin
                - stopped
                - stopped_by_creditworker
                - archived
            transitions:
                enable:
                    from: pending_deployment
                    to: active
                stop:
                    from: active
                    to: stopped
                start:
                    from: stopped
                    to: active
                suspend:
                    from: active
                    to: suspended
                admin_suspend:
                    guard: "is_granted('ROLE_SUPPORT')"
                    from: active
                    to: suspended_by_admin
                reactivate:
                    from: suspended
                    to: active
                admin_reactivate:
                    guard: "is_granted('ROLE_SUPPORT')"
                    from: suspended_by_admin
                    to: active
                suspended_to_archive:
                    from: suspended
                    to: archived
                suspended_by_admin_to_archive:
                    from: suspended_by_admin
                    to: archived
                stopped_to_archive:
                    from: stopped
                    to: archived
                cw_stop:
                    from: active
                    to: stopped_by_creditworker
                cw_start:
                    from: stopped_by_creditworker
                    to: active
        manage_organization_status:
            type: 'state_machine'
            audit_trail:
                enabled: true
            marking_store:
                type: 'method'
                property: 'status'
            supports:
                - App\Entity\Organization
            initial_marking: active
            places:
                - active
                - suspended
                - low_credit
                - no_credit
                - on_debt
                - pending_credit_addition # Staging state to add/remove credit to an organization
                - archived
                - pending_deletion
            transitions:
                suspend:
                    guard: "is_granted('ROLE_SUPPORT')"
                    from: active
                    to: suspended
                activate:
                    guard: "is_granted('ROLE_SUPPORT')"
                    from: suspended
                    to: active
                archive:
                    guard: "is_granted('ROLE_SUPPORT')"
                    from: suspended
                    to: archived
                reactivate:
                    from: archived
                    to: active
                delete:
                    guard: "is_granted('ROLE_SUPPORT')"
                    from: archived
                    to: pending_deletion
                consume_credit:
                    from: active
                    to: low_credit
                consume_low_credit:
                    from: low_credit
                    to: no_credit
                allow_credit_debt:
                    from: no_credit
                    to: on_debt
                suspend_from_debt:
                    from: on_debt
                    to: suspended
                suspend_subscription:
                    from: no_credit
                    to: suspended
                suspended_add_credit:
                    from: suspended
                    to: pending_credit_addition
                ondebt_add_credit:
                    from: on_debt
                    to: pending_credit_addition
                nocredit_add_credit:
                    from: no_credit
                    to: pending_credit_addition
                lowcredit_add_credit:
                    from: low_credit
                    to: pending_credit_addition