framework:
    workflows: 
        manage_app_deployments:
            type: 'state_machine'
            audit_trail:
                enabled: true
            marking_store:
                type: 'method'
                property: 'status'
            supports:
                - App\Entity\Deployments
            initial_marking: pending_deployment
            places:
                - pending_deployment
                - active
                - stopped
                - suspended
                - archived
                - pending_deletion
            transitions:
                start:
                    from: [pending_deployment, stopped, suspended]
                    to: active
                stop:
                    from: active
                    to: stopped
                suspend:
                    from: [active, pending_deployment]
                    to: suspended
                archive:
                    from: [suspended, stopped]
                    to: archived
                delete:
                    from: archived
                    to: pending_deletion
        manage_organization_status:
            type: 'state_machine'
            audit_trail:
                enabled: true
            marking_store:
                type: 'method'
                property: 'status'
            supports:
                - App\Entity\Organization
            initial_marking: active
            places:
                - active
                - low_credit
                - no_credit
                - on_debt
                - suspended
                - archived
                - pending_deletion
                - staging # A temporary buffer state for when a state needs to go back to a previous state
            transitions:
                suspend:
                    from: [active, on_debt, no_credit, staging]
                    to: suspended
                archive:
                    from: suspended
                    to: archived
                reactivate:
                    guard: "is_granted('ROLE_SUPPORT')"
                    from: archived
                    to: active
                delete:
                    guard: "is_granted('ROLE_SUPPORT')"
                    from: archived
                    to: pending_deletion
                consume_credit:
                    from: active
                    to: low_credit
                consume_low_credit:
                    from: low_credit
                    to: no_credit
                allow_credit_debt:
                    from: no_credit
                    to: on_debt
                add_transaction:
                    from: [suspended, active, low_credit, no_credit, on_debt]
                    to: staging
                activate:
                    from: staging
                    to: active
                go_to_lowcredit:
                    from: staging
                    to: low_credit
                go_to_nocredit:
                    from: staging
                    to: no_credit
                go_to_debt:
                    from: staging
                    to: on_debt