version: "3"
services:
  app:
    build:
      context: ./docker/development
      target: development
    depends_on:
      - db
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - xaymaapp:/var/www/app.xayma.sh
  
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
    volumes:
      - xaymaapp-db:/var/lib/mysql

volumes:
  xaymaapp:
  xaymaapp-db: