/**
 * AUTO-GENERATED FILE - NEVER EDIT MANUALLY
 * Generated by: npm run supabase:types
 *
 * This file is auto-generated from your Supabase database schema.
 * To regenerate: npm run supabase:types
 */

export type Database = {
  public: {
    Tables: Record<string, unknown>
    Views: Record<string, unknown>
    Functions: Record<string, unknown>
    Enums: Record<string, unknown>
    CompositeTypes: Record<string, unknown>
  }
  xayma_app: {
    Tables: Record<string, unknown>
    Views: Record<string, unknown>
    Functions: Record<string, unknown>
    Enums: Record<string, unknown>
    CompositeTypes: Record<string, unknown>
  }
}
